- app/models/boat.rb
- db/migrate/20200518123739_create_boats.rb
- test/models/boat_test.rb
j'ai ajouté le model baot merci de review & merge @loicredon @Tooommm
> ajout du model boat

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
> Creation UsersController avec method

- app/models/review.rb
- db/migrate/20200518125439_create_reviews.rb
- test/models/review_test.rb
> ajout du model review

- app/models/review.rb
- db/migrate/20200518125439_create_reviews.rb
- db/migrate/20200518130313_add_columns_to_users.rb
- test/models/review_test.rb
@Tooommm ajout des colonnes manquantes pour users
> Update users model

- app/models/boat.rb
to review & merge (relations pour boat)
@Tooommm
> ajout des relations pour boat

- app/models/extra_jointure.rb
- db/migrate/20200518132542_create_extra_jointures.rb
- test/models/extra_jointure_test.rb
@nlabrazi creation du model extra jointure
> creation extra jointure model

- app/controllers/boats_controller.rb
- app/controllers/users_controller.rb
- test/controllers/boats_controller_test.rb
- test/controllers/users_controller_test.rb
Hi @loicredon please can you merge and pull ma poule?
> Create boats controller

- app/controllers/boats_controller.rb
- app/controllers/deals_controller.rb
- app/controllers/users_controller.rb
- test/controllers/boats_controller_test.rb
- test/controllers/deals_controller_test.rb
- test/controllers/users_controller_test.rb
Hello lolo please merge and pupull ? @loicredon
> Create deals controller

- app/controllers/boats_controller.rb
- app/controllers/deals_controller.rb
- app/controllers/reviews_controller.rb
- test/controllers/boats_controller_test.rb
- test/controllers/deals_controller_test.rb
- test/controllers/reviews_controller_test.rb
Cher @loicredon ,
J'espère que tu vas bien.
Pourrais tu merge and pull mon code?
Bien à toi thomas.
> Create reviews controller

- app/controllers/boats_controller.rb
- app/controllers/deals_controller.rb
- app/controllers/extras_controller.rb
- app/controllers/reviews_controller.rb
- test/controllers/boats_controller_test.rb
- test/controllers/deals_controller_test.rb
- test/controllers/extras_controller_test.rb
- test/controllers/reviews_controller_test.rb
@loicredon coucou! merge and pull pleazzeeee
> Create extras controller

- app/controllers/boats_controller.rb
- app/controllers/deals_controller.rb
- app/controllers/extra_jointures_controller.rb
- app/controllers/extras_controller.rb
- app/controllers/reviews_controller.rb
- test/controllers/boats_controller_test.rb
- test/controllers/deals_controller_test.rb
- test/controllers/extra_jointures_controller_test.rb
- test/controllers/extras_controller_test.rb
- test/controllers/reviews_controller_test.rb
Hi @loicredon juste pour te partager peux tu pull and merge
> Create extra jointures controller

- app/models/review.rb
> ajout des relations to review

- app/models/deal.rb
- db/migrate/20200518135141_create_deals.rb
- test/models/deal_test.rb
@nlabrazi correction model deal, la bise gardoise
> creation model deal v2

- app/models/extra.rb
- db/migrate/20200518135645_create_extras.rb
- test/models/extra_test.rb
@nlabrazi creation du model Extra, comme toi
> creation model Extra v2

- app/models/deal.rb
@nlabrazi rajout de la relation deals / extras through extra_jointure
> ajout relation deal / extras

- app/models/user.rb
> ajout des relations users

- app/views/pages/home.html.erb
Hi @loicredon pleaze pour la view de la home !
> view pages home et nav bar

- .gitignore
- Gemfile
- Gemfile.lock
- config/environments/production.rb
hello @loicredon pourrais tu pour faire la merge de le changement si possible?
>  cloudinary setup gemfile, env, et production.rb

- app/models/boat.rb
- app/models/user.rb
> màj pour photos review/boat

- app/models/extra.rb
> rajout relation extras / deals

- config/routes.rb
> ajout des routes v1

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- db/schema.rb
> home fixed

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/devise/registrations/new.html.erb
- config/initializers/devise.rb
cotcot @loicredon please merge ça erge ASAP
> user creation solved

- app/controllers/boats_controller.rb
- app/controllers/deals_controller.rb
- app/views/shared/_navbar.html.erb
- config/routes.rb
> links changes routes

- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/landing.html.erb
- config/routes.rb
@loicredon merge ASP por favor
> landing backgroun fixed

- app/views/boats/index.html.erb
- app/views/users/show.html.erb
to review @Tooommm ASAP & MERGE TOO
> ajout des edit pages

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_landing.scss
- app/views/pages/landing.html.erb
> Landing shit

- .gitignore
- app/controllers/boats_controller.rb
- app/models/boat.rb
- app/views/boats/new.html.erb
- db/migrate/20200519154708_rename_column_type.rb
- db/schema.rb
@nlabrazi valide ma branche vieille branche
> Create view boat

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> home en cours

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
to merge si vous voulez une home pure html @Tooommm
> font des enfers my men

- app/controllers/boats_controller.rb
- app/models/boat.rb
- app/views/pages/home.html.erb
> landing encours

- app/controllers/boats_controller.rb
- app/views/boats/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
> corrections routes

- app/views/pages/home.html.erb
> home dynamique

- app/views/boats/show.html.erb
@nlabrazi merge mois ça rapido
> add bob show part2

- app/controllers/boats_controller.rb
- app/views/boats/new.html.erb
- app/views/pages/home.html.erb
> fixed boat controller

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/boats/show.html.erb
> modif show part 3

- app/views/boats/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
> add footer

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/boats_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/views/boats/new.html.erb
- app/views/boats/show.html.erb
- app/views/dashboards/boats.html.erb
- app/views/dashboards/deals.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- config/routes.rb
- db/migrate/20200521031756_add_coordinates_to_boats.rb
- db/schema.rb
- package.json
- yarn.lock
> bonne chance pour la review

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/devise/registrations/edit.html.erb
- app/views/pages/home.html.erb
> les belles images

- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/boats/show.html.erb
Reverts nlabrazi/veryboattrip#64
> Revert "add show boat"

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/boats/show.html.erb
- app/views/layouts/application.html.erb
> show boat ok
